[package]
name = "pd-federation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pd-core = { workspace = true }
pd-http = { workspace = true }

bubble-bath = { workspace = true }
error-stack = { workspace = true }
http = { workspace = true }
mime = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
sonic-rs = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
typed-builder = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }

[dev-dependencies]
bytes = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }

[lints]
workspace = true
